<a href="https://colab.research.google.com/github/MBSingh2038/KAG-Conversion_NumPy-Project/blob/main/Project_2_KAG_Conversion_Data_1_27.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#Loading a main data file from excel
main_data_File = "/content/KAG_Conversion_Data.csv"

In [12]:
import numpy as np
main_data = np.genfromtxt(main_data_File, delimiter = ",", skip_header = 1)
data_str = np.genfromtxt(main_data_File,delimiter = ",",skip_header = 1,dtype=str)
print("\nData :\n",main_data)


Data :
 [[7.08746000e+05 9.16000000e+02 1.03916000e+05 ... 1.42999995e+00
  2.00000000e+00 1.00000000e+00]
 [7.08749000e+05 9.16000000e+02 1.03917000e+05 ... 1.82000002e+00
  2.00000000e+00 0.00000000e+00]
 [7.08771000e+05 9.16000000e+02 1.03920000e+05 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 ...
 [1.31441200e+06 1.17800000e+03 1.79979000e+05 ... 4.02899995e+01
  2.00000000e+00 0.00000000e+00]
 [1.31441400e+06 1.17800000e+03 1.79981000e+05 ... 1.98710001e+02
  8.00000000e+00 2.00000000e+00]
 [1.31441500e+06 1.17800000e+03 1.79982000e+05 ... 1.65609999e+02
  5.00000000e+00 2.00000000e+00]]


In [13]:
#Finding number of unique ID an campaigns
xyz = main_data[:,1]
unique_id = np.unique(xyz)
print(unique_id)

[ 916.  936. 1178.]


In [14]:
import numpy as np

unique_id,count = np.unique(xyz, return_counts =True)
print("The unique ID's are:- ",unique_id)
print("The number of unique ID's are:- ",count)

The unique ID's are:-  [ 916.  936. 1178.]
The number of unique ID's are:-  [ 54 464 625]


In [16]:
print("The number of times each unique ID rans:- ")
for i in range(len(unique_id)):
  
  print('\n{} ran {} times'.format(unique_id[i],count[i]))

The number of times each unique ID rans:- 

916.0 ran 54 times

936.0 ran 464 times

1178.0 ran 625 times


In [23]:
from numpy.ma.extras import unique
age_group = data_str[:,3]
print("The age group are:- \n",age_group)

#Counting the number of age groups
count_age_group = np.unique(age_group)

#Displaying the age groups
print("\nThe unique age groups are:- \n",count_age_group)

#Displaying the number of unique age groups
print("\nThere are", len(count_age_group), "age groups in the campaign",)

The age group are:- 
 ['30-34' '30-34' '30-34' ... '45-49' '45-49' '45-49']

The unique age groups are:- 
 ['30-34' '35-39' '40-44' '45-49']

There are 4 age groups in the campaign


In [24]:
#Finding average, minimum and maximum amount spent on the ads
time_spent =main_data[:, 8]
print(time_spent)

#Finding and displaying average time
average_time_spend = time_spent.mean()
print("Average Time Spend by the users = ", round(average_time_spend,2))

#Finding and displaying minimum time
min_time_spend = time_spent.min()
print("Minimum Time Spend by the users = ", round(min_time_spend,2))

#Finding and displaying maximum time
max_time_spend = time_spent.max()
print("Maximum Time Spend by the users = ", round(max_time_spend,2))

[  1.42999995   1.82000002   0.         ...  40.28999949 198.7100005
 165.6099987 ]
Average Time Spend by the users =  51.36
Minimum Time Spend by the users =  0.0
Maximum Time Spend by the users =  639.95


In [26]:
#Finding the ID of the Ad having maximum number of clicks
number_of_clicks= main_data[:, 7]
id = main_data[:, 0]
print(number_of_clicks)
print("ID = ",id)

#finding and displaying the maximum number of clicks
max_num_of_clicks = number_of_clicks.max()
print("Maximum number of clicks = ", max_num_of_clicks, "times")

print("The ID having the number of clicks is : ",id[number_of_clicks == max_num_of_clicks])

[  1.   2.   0. ...  28. 135. 114.]
ID =  [ 708746.  708749.  708771. ... 1314412. 1314414. 1314415.]
Maximum number of clicks =  421.0 times
The ID having the number of clicks is :  [1121814.]


In [31]:
#Finding the number of people who bought the product after seeing the ad with most clicks
approved_conversion = main_data[:, 10]
print(approved_conversion)
max_num_of_approved_conversion = approved_conversion.max()
print("Maximum Number of approved conversion = ", max_num_of_approved_conversion)

number_of_persons = approved_conversion[number_of_clicks == max_num_of_clicks]
print("The number of persons that bought the product after seeing the add with most clicks = ", number_of_persons)
if number_of_persons>max_num_of_approved_conversion:
  print("Yes the maximum number of purchases presents in the dataset")
else:
  print("No the maximum number of purchases presents in the dataset")

[1. 0. 0. ... 0. 2. 2.]
Maximum Number of approved conversion =  21.0
The number of persons that bought the product after seeing the add with most clicks =  [13.]
No the maximum number of purchases presents in the dataset


In [33]:
#Finding the details of the product having maximum number of purchases
print("The details of product having maximu number of purchases are:- ")
main_data[approved_conversion==21]


The details of product having maximu number of purchases are:- 


array([[1.12110400e+06, 1.17800000e+03, 1.44533000e+05,            nan,
                   nan, 1.60000000e+01, 2.08066600e+06, 2.02000000e+02,
        3.60150001e+02, 4.00000000e+01, 2.10000000e+01]])